import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { getRepositories, Repository } from "../services/github";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [repositories, setRepositories] = useState<Repository[]>([]);

  useEffect(() => {
    getRepositories().then(({ items, total_count }) => {
      setRepositories(items);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Github Trending Repositories</h1>
      </main>

      {repositories.map((r) => (
        <div>{r.name}</div>
      ))}
    </div>
  );
};

export default Home;
