import Head from "next/head";
import type { NextPage } from "next";
import styled from "styled-components";
import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";
import RepositoryList from "../components/repository-list";
import { getRepositories, Repository } from "../services/github";

const Main = styled.main`
  margin: 0 auto;
  width: 80vw;
`;

const Home: NextPage = () => {
  const [repositories, setRepositories] = useState<Repository[]>([]);

  useEffect(() => {
    getRepositories().then(({ items, total_count }) => {
      setRepositories(items);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main className={styles.main}>
        <h1 className={styles.title}>Github Trending Repositories</h1>

        <RepositoryList />
      </Main>
    </div>
  );
};

export default Home;
