import Head from "next/head";
import type { NextPage } from "next";
import styled from "styled-components";

import styles from "../styles/Home.module.css";
import RepositoryList from "../components/repository-list";

const Main = styled.main`
  margin: 0 auto;
  width: 80vw;
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main className={styles.main}>
        <h1 className={styles.title}>Github Trending Repositories</h1>

        <RepositoryList />
      </Main>
    </div>
  );
};

export default Home;
